# このバージョンがインストールされているかどうかを処理の判定基準とする
virtualbox_version: 6.1.14
# VBoxGuestAdditions_{{ virtualbox_version }}.isoファイルのチェックサム（http://download.virtualbox.org/virtualbox/{{ virtualbox_version }}/SHA256SUMS）
iso_checksum: "sha256:dd9f176abb89043c01cea7ec7e20130e76db71bd83beafeb2dc5858d4c9c86cd"
# isoファイルのダウンロードディレクトリ
iso_download_path: "/opt/vboxguest"
# isoファイルのマウントパス
iso_mount_path: /mnt/virtualbox
# isoファイルのダウンロード先パス
virtualbox_iso_path: "{{iso_download_path}}/VBoxGuestAdditions_{{virtualbox_version}}.iso"
# x11ありでインストールする場合に変数と値を定義しておく
virtualbox_x11: no
