# このバージョンがインストールされているかどうかを処理の判定基準とする
virtualbox_version: 6.1.16
# VBoxGuestAdditions_{{ virtualbox_version }}.isoファイルのチェックサム（http://download.virtualbox.org/virtualbox/{{ virtualbox_version }}/SHA256SUMS）
iso_checksum: "sha256:88db771a5efd7c048228e5c1e0b8fba56542e9d8c1b75f7af5b0c4cf334f0584"
# isoファイルのダウンロードディレクトリ
iso_download_path: "/opt/vboxguest"
# isoファイルのマウントパス
iso_mount_path: /mnt/virtualbox
# isoファイルのダウンロード先パス
virtualbox_iso_path: "{{iso_download_path}}/VBoxGuestAdditions_{{virtualbox_version}}.iso"
# x11ありでインストールする場合に変数と値を定義しておく
virtualbox_x11: no
