- name: "Go | Goのインストーラーをダウンロードする"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  get_url:
    url: "{{ go.tarball.file.url }}/{{ go.tarball.file.name }}"
    dest: "{{ go.tarball.file.dest }}/{{ go.tarball.file.name }}"

- name: "Go | Goのインストーラーがダウンロード済か確認する"
  become: yes
  ignore_errors: yes
  stat:
    path: "{{ go.tarball.file.dest }}/{{ go.tarball.file.name }}"
  register: go_tarball_dest_path

- block:

  - name: "Go | インストール済のGoを削除する"
    become: yes
    ignore_errors: yes
    file:
      name: /usr/local/go
      state: absent

  - name: "Go | Goのインストーラーを展開する"
    become: yes
    ignore_errors: "{{ ansible_check_mode }}"
    unarchive:
      remote_src: yes
      src: "{{ go.tarball.file.dest }}/{{ go.tarball.file.name }}"
      dest: /usr/local

  - name: "Go | Goをパスに追加するスクリプトをコピーする"
    become: yes
    ignore_errors: "{{ ansible_check_mode }}"
    copy:
      src: add_path_golang_bin
      dest: /etc/add_path_golang_bin

  - name: "Go | Goのパス追加スクリプトをユーザーのシェル設定ファイルに読み込ませる"
    ignore_errors: "{{ ansible_check_mode }}"
    shell:
      cmd: |
        cat $HOME/.bashrc | grep "/etc/add_path_golang_bin" >/dev/null
        if [ $? -eq 0 ]; then
          echo "already changed."
        else
          echo ". /etc/add_path_golang_bin" >> $HOME/.bashrc
        fi

  when: go_tarball_dest_path.stat.exists