- name: "共通 | tmuxをインストールする"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  apt:
    name: tmux
    state: present

- name: "共通 | xselをインストールする"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  apt:
    name: xsel
    state: present

- name: "共通 | tmuxの設定ファイルをコピーする"
  ignore_errors: "{{ ansible_check_mode }}"
  copy:
    src: .tmux.conf
    dest: "~/.tmux.conf"
