- name: "共通 | vimをインストールする"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  apt:
    name: vim
    state: present

- name: "共通 | viでvimを呼び出せるようにする"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  shell:
    cmd: |
      cat "{{ etc.profile.file.path }}" | grep "alias vi='vim'" >/dev/null
      if [ $? -eq 0 ]; then
        echo "already changed."
      else
        echo -e "\nalias vi='vim'" >> "{{ etc.profile.file.path }}"
        . "{{ etc.profile.file.path }}"
      fi

- name: "共通 | vimrcカスタマイズ用のファイルをコピーする"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  copy:
    src: vimrc_ext
    dest: "{{ vim.rc_ext.dist.file.path }}"

- name: "共通 | vimrcカスタマイズ内容を設定ファイルへ追記する"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  shell:
    cmd: |
      cat "{{ vim.rc.file.path }}" | grep "set nocompatible" >/dev/null
      if [ $? -eq 0 ]; then
        echo "already changed."
      else
        cat "{{ vim.rc_ext.dist.file.path }}" >> "{{ vim.rc.file.path }}"
      fi

- name: "共通 | vimrcカスタマイズ用のファイルを削除する"
  become: yes
  ignore_errors: no
  file:
    path: "{{ vim.rc_ext.dist.file.path }}"
    state: absent
