- name: "共通 | パッケージを最新化する"
  become: yes
  apt:
    name: '*'
    state: latest

- name: "共通 | すべてのパッケージをアップグレードする"
  become: yes
  apt:
    upgrade: dist

- name: "共通 | 不要になったパッケージを削除する"
  become: yes
  apt:
    autoremove: yes
