- hosts: all
  roles:
    - update_upgrade
    - customize_shell_prompt
    - vim
    - ntp_client
    - timezone
    - locale_japanese
    - keychain-ssh-keys
    - ssh-settings
    - tmux
    - docker
    - nvm
    - golang
    - ghq
    - peco
    - ghq-peco-alias
    - xfce4
    - xdg-user-dirs-gtk
    - ibus_mozc
    - xrdp
    - google-chrome
    - jdk
