- name: "ghq | goでインストールする"
  ignore_errors: "{{ ansible_check_mode }}"
  shell:
    cmd: /usr/local/go/bin/go get github.com/x-motemen/ghq

- name: "ghq | Goのパッケージをパスに追加するスクリプトをコピーする"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  copy:
    src: add_path_golang_pkg
    dest: /etc/add_path_golang_pkg

- name: "ghq | Goのパッケージパス追加スクリプトをユーザーのシェル設定ファイルに読み込ませる"
  ignore_errors: "{{ ansible_check_mode }}"
  shell:
    cmd: |
      cat $HOME/.bashrc | grep "/etc/add_path_golang_pkg" >/dev/null
      if [ $? -eq 0 ]; then
        echo "already changed."
      else
        echo ". /etc/add_path_golang_pkg" >> $HOME/.bashrc
      fi
