- name: "ghq-peco-alias | コマンドのエイリアスを追加する"
  ignore_errors: "{{ ansible_check_mode }}"
  shell:
    cmd: |
      cat $HOME/.bashrc | grep -E "^alias gp='cd \\$\(ghq root\)/\\$\(ghq list \| peco\)'$" >/dev/null
      if [ $? -eq 0 ]; then
        echo "already changed."
      else
        echo -n "\n" >> $HOME/.bashrc
        echo 'alias gp='\''cd $(ghq root)/$(ghq list | peco)'\' >> $HOME/.bashrc
      fi