- name: "Git | 最新版をインストールするためPPAを追加する"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  apt_repository:
    repo: ppa:git-core/ppa

- name: "Git | aptのキャッシュを更新する"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  apt:
    update_cache: yes

- name: "Git | インストールする"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  apt:
    name: git
    state: present
