# 追加の参考URL https://symfoware.blog.fc2.com/blog-entry-2446.html
# Ubuntu20.04ではlibvirt-binが存在しなかった
- name: "Cloud Foundry CF Dev | 必要なパッケージをインストールする"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  apt:
    name: 
      - qemu-kvm
      - libvirt-clients
      - libvirt-daemon-system
      - bridge-utils 
      - virt-manager
      - libvirt-doc
    state: present

- name: "Cloud Foundry CF Dev | インストールする"
  ignore_errors: "{{ ansible_check_mode }}"
  shell: cf install-plugin -r CF-Community cfdev -f
