- name: "Docker | パッケージを最新化する"
  become: yes
  apt:
    name: '*'
    state: latest

- name: "Docker | aptがHTTPS経由でパッケージへアクセスできるように必要なパッケージをインストールする"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

- name: "Docker | Dockerの公式PGPキーを追加する"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "Docker | ディストリビューションのLSB情報を取得する"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  shell: echo $(lsb_release -cs)
  register: lsb_release_info

- name: "Docker | ディストリビューションのLSB情報をデバッグ出力する"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  debug:
    msg: "{{ lsb_release_info.stdout }}"

- name: "Docker | 安定版のリポジトリを追加する"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release_info.stdout }} stable
    state: present

- name: "Docker | リポジトリ追加後に再びパッケージを最新化する"
  become: yes
  apt:
    name: '*'
    state: latest

- name: "Docker | インストールする"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: "Docker | グループを追加する"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  user:
    name: "{{ ansible_user }}"
    append: yes
    groups: docker

- name: "Docker | サービスを有効化・起動する"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  systemd:
    name: docker
    enabled: yes
    state: started
