- name: "VirtualBox Guest Additions | 対象のバージョンがインストールされていることを確認する"
  become: true
  ignore_errors: yes
  shell: modinfo vboxguest 2>/dev/null|awk '/^version/{print $2}'
  register: vbox_guest_version
  changed_when: vbox_guest_version.stdout != virtualbox_version

- block:

  - name: "VirtualBox Guest Additions | ディレクトリ「{{iso_download_path}}」が存在することを確認する（なければ作成）"
    become: true
    ignore_errors: "{{ ansible_check_mode }}"
    file:
      path: "{{iso_download_path }}"
      state: directory
      mode: '0755'

  - name: "VirtualBox Guest Additions | isoファイルがダウンロード済か確認する"
    become: true
    ignore_errors: yes
    stat: path="{{virtualbox_iso_path}}"
    register: file_path

  - name: "VirtualBox Guest Additions | isoファイルをダウンロードする"
    become: true
    ignore_errors: "{{ ansible_check_mode }}"
    get_url:
      url: http://download.virtualbox.org/virtualbox/{{ virtualbox_version}}/VBoxGuestAdditions_{{virtualbox_version}}.iso
      dest: "{{virtualbox_iso_path}}"
      checksum: "{{iso_checksum}}"
    when: (not file_path.stat.exists)

  - name: "VirtualBox Guest Additions | isoファイルをループバックでマウントする"
    become: true
    ignore_errors: "{{ ansible_check_mode }}"
    mount:
      name: "{{iso_mount_path}}"
      src: "{{virtualbox_iso_path}}"
      opts: "ro,loop"
      fstype: iso9660
      state: mounted

  - name: "VirtualBox Guest Additions | コンパイルに必要なパッケージをインストールする"
    become: true
    ignore_errors: "{{ ansible_check_mode }}"
    apt:
      name:
        - build-essential
        - gcc
        - make
        - perl
      state: present

  - name: "VirtualBox Guest Additions | 現在インストールされているVirtualBox関連パッケージを取得する"
    become: true
    ignore_errors: "{{ ansible_check_mode }}"
    shell: 
      cmd: dpkg -l | grep vbox | awk '{ print $1}'
      warn: no
    register: installed_packages

  - name: "VirtualBox Guest Additions | 現在インストールされているVirtualBox関連パッケージをアンインストールする"
    become: true
    ignore_errors: "{{ ansible_check_mode }}"
    yum:
      name: "{{item}}"
      state: absent
    with_items: "{{installed_packages.stdout_lines}}"

  - name: "VirtualBox Guest Additions | アンインストールを試行する"
    become: true
    ignore_errors: yes
    shell: "/bin/bash {{iso_mount_path}}/VBoxLinuxAdditions.run uninstall --force"

  - name: "VirtualBox Guest Additions | x11なしでインストールする"
    become: true
    ignore_errors: yes
    shell: "/bin/bash {{iso_mount_path}}/VBoxLinuxAdditions.run --nox11"
    when: (virtualbox_x11 is undefined) or (not virtualbox_x11)

  - name: "VirtualBox Guest Additions | x11ありでインストールする"
    become: true
    ignore_errors: yes
    shell: "/bin/bash {{iso_mount_path}}/VBoxLinuxAdditions.run"
    when: (virtualbox_x11 is defined) and virtualbox_x11

  - name: "VirtualBox Guest Additions | isoファイルを取り出す"
    become: true
    ignore_errors: "{{ ansible_check_mode }}"
    mount:
      name: "{{iso_mount_path}}"
      src: "{{virtualbox_iso_path}}"
      opts: "ro,loop"
      fstype: iso9660
      state: absent

  - name: "VirtualBox Guest Additions | ログファイルや中間生成ファイル、isoファイルを削除する"
    become: true
    ignore_errors: "{{ ansible_check_mode }}"
    file:
      name: "{{ item }}"
      follow: yes
      state: absent
    with_items:
      - "{{ iso_download_path }}"
      - "/opt/VBoxGuestAdditions-{{ virtualbox_version }}/src"
      - "/usr/src/vboxguest-{{ virtualbox_version }}"
      - /var/log/vboxadd-install.log
      - /var/log/vboxadd-install-x11.log
      - /var/log/VBoxGuestAdditions.log

  - name: "VirtualBox Guest Additions | isoファイルのfstabエントリーを削除する"
    become: true
    ignore_errors: "{{ ansible_check_mode }}"
    lineinfile: >
      dest=/etc/fstab
      regexp='^{{ iso_download_path }}'
      line='{{ iso_download_path }}	{{ iso_mount_path }}	iso9660	ro,loop	0	0'
      state=absent

  - name: "VirtualBox Guest Additions | グループを追加する"
    become: true
    ignore_errors: "{{ ansible_check_mode }}"
    user:
      name: "{{ ansible_user }}"
      append: yes
      groups: vboxsf

  - block:

    - name: "VirtualBox Guest Additions | 再起動する"
      become: true
      ignore_errors: "{{ ansible_check_mode }}"
      reboot:

    - name: "VirtualBox Guest Additions | 再起動したことを確認する"
      debug:
        msg: "再起動しました"
    
    when: inventory_hostname != 'localhost'

  - name: "VirtualBox Guest Additions | 再起動を促す"
    debug:
      msg: "再起動してください"
    when: inventory_hostname == 'localhost'

  when: (vbox_guest_version.stdout != virtualbox_version)
